spring:
  datasource:
    url: jdbc:mysql://1Panel-mysql-s4pB:3306/news-kiosk?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: tt2E5r1WLnzhW
    driver-class-name: com.mysql.cj.jdbc.Driver

# AutoTable配置，根据实体类自动生成表
auto-table:
  # 启用自动维护表功能
  enable: false

# Cool相关配置
cool:
  # 初始化数据
  initData: false

# 文档
springdoc:
  api-docs:
    #是否开启文档功能 本地为了配合eps功能不可关闭
    enabled: true

# 设置日志级别
logging:
  level:
    com.cool: error